
name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release-crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: publish package to crates
        run: |
          cargo package
          cargo publish --token ${{ secrets.CARGO_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Build
        run: cargo build --all --release && strip target/release/convfmt && mv target/release/convfmt target/release/convfmt_amd64

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: convfmt_amd64
          path: target/release/convfmt_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/convfmt_amd_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/convfmt_amd64
          asset_name: convfmt_amd64
          tag: ${{ github.ref }}
          overwrite: true

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release
      
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: convfmt.exe
          path: target/release/convfmt.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/convfmt.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/convfmt.exe
          asset_name: convfmt.exe
          tag: ${{ github.ref }}
          overwrite: true
  
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/convfmt && mv target/release/convfmt target/release/convfmt_darwin

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: convfmt_darwin
          path: target/release/convfmt_darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/convfmt_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/convfmt_darwin
          asset_name: convfmt_darwin
          tag: ${{ github.ref }}
          overwrite: true
